import {
  TEST_SLACK_WEBHOOK_URL_PATH as _TEST_SLACK_WEBHOOK_URL_PATH,
  SLACK_WEBHOOK_URL_PATH as _SLACK_WEBHOOK_URL_PATH,
  TEST_GOOGLE_FORM_KEY as _TEST_GOOGLE_FORM_KEY,
  GOOGLE_FORM_KEY as _GOOGLE_FORM_KEY,
  TEST_GOOGLE_FORM_MAPPING_TIMESTAMP,
  TEST_GOOGLE_FORM_MAPPING_TOPIC,
  TEST_GOOGLE_FORM_MAPPING_APP,
  TEST_GOOGLE_FORM_MAPPING_OPERATING_SYSTEM,
  TEST_GOOGLE_FORM_MAPPING_DEVICE_MODEL,
  TEST_GOOGLE_FORM_MAPPING_MESSAGE,
  TEST_GOOGLE_FORM_MAPPING_APP_VERSION,
  GOOGLE_FORM_MAPPING_TIMESTAMP,
  GOOGLE_FORM_MAPPING_TOPIC,
  GOOGLE_FORM_MAPPING_APP,
  GOOGLE_FORM_MAPPING_OPERATING_SYSTEM,
  GOOGLE_FORM_MAPPING_DEVICE_MODEL,
  GOOGLE_FORM_MAPPING_MESSAGE,
  GOOGLE_FORM_MAPPING_APP_VERSION
} from '@tetherto/pearpass-lib-constants'

import { isDev } from '../utils/envGetter'

export const SLACK_WEBHOOK_URL_PATH = isDev()
  ? _TEST_SLACK_WEBHOOK_URL_PATH
  : _SLACK_WEBHOOK_URL_PATH

export const GOOGLE_FORM_KEY = isDev()
  ? _TEST_GOOGLE_FORM_KEY
  : _GOOGLE_FORM_KEY

export const GOOGLE_FORM_MAPPING = isDev()
  ? {
      timestamp: TEST_GOOGLE_FORM_MAPPING_TIMESTAMP,
      topic: TEST_GOOGLE_FORM_MAPPING_TOPIC,
      app: TEST_GOOGLE_FORM_MAPPING_APP,
      operatingSystem: TEST_GOOGLE_FORM_MAPPING_OPERATING_SYSTEM,
      deviceModel: TEST_GOOGLE_FORM_MAPPING_DEVICE_MODEL,
      message: TEST_GOOGLE_FORM_MAPPING_MESSAGE,
      appVersion: TEST_GOOGLE_FORM_MAPPING_APP_VERSION
    }
  : {
      timestamp: GOOGLE_FORM_MAPPING_TIMESTAMP,
      topic: GOOGLE_FORM_MAPPING_TOPIC,
      app: GOOGLE_FORM_MAPPING_APP,
      operatingSystem: GOOGLE_FORM_MAPPING_OPERATING_SYSTEM,
      deviceModel: GOOGLE_FORM_MAPPING_DEVICE_MODEL,
      message: GOOGLE_FORM_MAPPING_MESSAGE,
      appVersion: GOOGLE_FORM_MAPPING_APP_VERSION
    }
