name: Lint check

on:
  push:
    branches: [ main, dev ]
  pull_request_target:
    branches: [ main, dev ]

permissions:
  contents: read
  packages: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      # Step : Run the Type Check (e.g., TypeScript)
      # If there are type errors, the pipeline stops here and fails.
      - name: Type Check
        run: npx tsc --noEmit
        run: |
          npm run lingui:extract
          npm run lingui:compile
          npx tsc --noEmit
